language: erlang
otp_release:
- 17.0
before_install:
- git clone https://github.com/elixir-lang/elixir
- cd elixir
- git checkout v0.14.0
- cd ..
- make -C elixir
before_script:
- export PATH=`pwd`/elixir/bin:$PATH
- mix deps.get
script:
- MIX_ENV=all mix test
env:
  global:
  - secure: IabOSaV2Y/FM09Ka0MQ+64mKdkn4mJgcQAVIHXOCWpoSqQsoTg9lgqt+2Leo9rGd3WnikeuGtWWQURiN0uQT1zjCpA14jqsAfQrVLkeRjp4n7axopwZB8xOC9+gEm/W4V3RKWoNVvY2r6qjMr03dfGMGmF6UNIFSD+ehBMutwdg=
  - secure: ammR97lGPt44kWG2h2kuOTjnOZP3Gi1IV3xfs04sX7NX6dmqP+WTjN62/5FtSPcGrWfIRyfsJ4WMyYRfcZsq9XpncWcH77AkS0vxDc18qvp8ddRnwjbBdIWWG9+PosuIMVy7l/UHFYit89O6gXx/Ezf0fnVVwrzJcQese+eOYXU=
