language: erlang
env:
  - ELIXIR="v0.14.0"
  - ELIXIR="v0.14.1"
  - ELIXIR="v0.14.2"
otp_release:
  - 17.0
before_install:
  - wget http://s3.hex.pm/builds/elixir/$ELIXIR.zip
  - unzip -d elixir $ELIXIR.zip 
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix deps.get
script:
  - MIX_ENV=all mix test
env:
  global:
  - secure: IabOSaV2Y/FM09Ka0MQ+64mKdkn4mJgcQAVIHXOCWpoSqQsoTg9lgqt+2Leo9rGd3WnikeuGtWWQURiN0uQT1zjCpA14jqsAfQrVLkeRjp4n7axopwZB8xOC9+gEm/W4V3RKWoNVvY2r6qjMr03dfGMGmF6UNIFSD+ehBMutwdg=
  - secure: ammR97lGPt44kWG2h2kuOTjnOZP3Gi1IV3xfs04sX7NX6dmqP+WTjN62/5FtSPcGrWfIRyfsJ4WMyYRfcZsq9XpncWcH77AkS0vxDc18qvp8ddRnwjbBdIWWG9+PosuIMVy7l/UHFYit89O6gXx/Ezf0fnVVwrzJcQese+eOYXU=
  - secure: QaE679K3I2JlLA8GH9HAoE1OSK1Kg7hXiQ7Gnn/HQ6YUKWolgDoubUSSvurlf/3cP/3WGWN83OLnTuWZnRACx1/izihbe0VbYzL/HUxY1NO66Ui6B5BNGrgh/NVAx3DxCy5SaLJXjmcn82jltCvOcadXMqpZVryRagYx0ajpR70=
  - secure: XVwQh93MoR++FfEYcfM81ZbEi2KumWCOK1yN0Fi8SDwXgo20stfZGPEDbRZaTZp/mCktBKeaDTo/AK+FVHmoflCCVuyOAHemuhjlXgWX1urt6/Juiqg3wu+rZ+y3cohuYB+CXBKjge98zO+ExHEcTdhcbxwn0VP3lBm5dreExA8=
  - secure: Ym/2N5mywg0DaY858ksWZfrDCvccQ5RdLVe5JEmGxKJoMTLFjv9XiCN5BB0siBmxvbNje2PbjIlyB661SVJBbLjLYq4NpUTwO5Rsq/LgbagQnK0aXW+fHhCwV7e4d0raXjQQkrpy6/fixEAf04VpcUUvO1kzDulflMjcMgNh4tI=
notifications:
  email:
  - skyler@dwolla.com
