language: erlang
otp_release:
   - 17.0
before_install:
   - git clone https://github.com/elixir-lang/elixir
   - git checkout v0.14.0
   - make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script:
   - mix deps.get 
   - mix test
